// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app/test": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app"
                ],
                "summary": "app test 接口",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "手机\\邮箱验证码登录",
                "parameters": [
                    {
                        "description": "用户登录",
                        "name": "LoginReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserLoginReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "请求ID",
                        "name": "request_id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/user.UserLoginResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "user.UserLoginReq": {
            "type": "object",
            "required": [
                "account",
                "area_code"
            ],
            "properties": {
                "account": {
                    "description": "登录账号",
                    "type": "string"
                },
                "area_code": {
                    "description": "区号,如果是手机号 传 区号，如果是邮箱 传 邮箱服务商 gmail、qq、outlook 等",
                    "type": "string"
                },
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "password": {
                    "description": "登录密码，前端 必须进行 sha256 hash 后传过来 【小写】\n1. 如果账号存在的时候登录，密码 或者验证码必须有一个\n2. 如果获取 验证码登录的时候，获取验证码返回的是新用户，需要设置密码，也是使用该字段",
                    "type": "string"
                }
            }
        },
        "user.UserLoginResp": {
            "type": "object",
            "properties": {
                "is_new": {
                    "description": "是否是新用户",
                    "type": "boolean"
                },
                "token": {
                    "description": "用户登录成功的 token",
                    "type": "string"
                },
                "user_sys_id": {
                    "description": "uid 用户id",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
