definitions:
  _struct.MobilePhoneAccountInfo:
    properties:
      area_code:
        description: 区号
        type: string
      phone:
        description: 手机号
        type: string
    type: object
  rc.GetUserTokenReq:
    type: object
  rc.GetUserTokenResp:
    properties:
      token:
        type: string
      user_sys_id:
        description: uid 用户id
        type: string
    type: object
  response.SmsCountryListResp:
    properties:
      area_code:
        description: 国家手机区号
        type: string
      code:
        description: 国家 code
        type: string
      en_name:
        description: 英文名称
        type: string
      flag_url:
        description: 国旗 url
        type: string
      name:
        description: 国家名称
        type: string
    type: object
  room.CreateRoomReq:
    type: object
  room.CreateRoomResp:
    properties:
      info:
        allOf:
        - $ref: '#/definitions/room.RoomBaseInfo'
        description: 房间的基本信息
    type: object
  room.RoomBaseInfo:
    properties:
      cover:
        description: 房间封面
        type: string
      im_group_id:
        description: IM群组ID
        type: integer
      live_status:
        description: 直播状态 open:直播中 close:未直播
        type: string
      name:
        type: string
      notice:
        description: 房间公告
        type: string
      status:
        description: 房间状态 open:正常 close:禁用
        type: string
      sys_id:
        description: 房间 SysID
        type: string
    type: object
  room.RoomBasenfoReq:
    properties:
      room_sys_id:
        description: 房间的 sysID
        type: string
    required:
    - room_sys_id
    type: object
  room.RoomBasenfoResp:
    properties:
      info:
        allOf:
        - $ref: '#/definitions/room.RoomBaseInfo'
        description: 房间的基本信息
    type: object
  room.RoomListReq:
    properties:
      page:
        description: 第几页，从 1 开始
        type: integer
      page_size:
        description: 每页的大小
        type: integer
    required:
    - page
    - page_size
    type: object
  room.RoomListResp:
    properties:
      list:
        items:
          $ref: '#/definitions/room.RoomBaseInfo'
        type: array
      total:
        description: 房间总条数
        type: integer
    type: object
  sys.GetSysConfigReq:
    type: object
  sys.GetSysConfigResp:
    properties:
      agora_app_id:
        description: 声望 app id
        type: string
      rc_app_key:
        description: 融云 app key
        type: string
    type: object
  user.AccountBindInfo:
    properties:
      mobile_phone:
        $ref: '#/definitions/_struct.MobilePhoneAccountInfo'
    type: object
  user.AccountVerifyCodeReq:
    properties:
      code:
        description: 验证码
        type: string
      identity_type:
        description: 登录类型，mobile_phone、email 目前只有 mobile_phone
        type: string
    required:
    - code
    - identity_type
    type: object
  user.AccountVerifyCodeResp:
    properties:
      is_verify:
        description: 是否验证通过
        type: boolean
      verify_hash:
        description: 本次验证的 hash, 后续重置密码使用
        type: string
    type: object
  user.ChangePasswordReq:
    properties:
      identity_type:
        description: 登录类型，mobile_phone、email 目前只有 mobile_phone
        type: string
      new_password:
        description: 新密码 前端 必须进行 sha256 hash 后传过来 【小写】
        type: string
      password:
        description: 登录密码，前端 必须进行 sha256 hash 后传过来 【小写】
        type: string
    required:
    - identity_type
    - new_password
    - password
    type: object
  user.ChangePasswordResp:
    type: object
  user.GetUserInfoReq:
    properties:
      return_account_bind_list:
        description: 是否返回账号绑定列表，默认不返回
        type: boolean
      return_fans_data:
        description: 是否返回粉丝数据
        type: boolean
    type: object
  user.GetUserInfoResp:
    properties:
      account_bind_info:
        allOf:
        - $ref: '#/definitions/user.AccountBindInfo'
        description: 绑定账号信息
      avatar:
        description: 头像
        type: string
      birthday:
        description: 生日年-月-日
        type: string
      fan_data:
        allOf:
        - $ref: '#/definitions/user.UserFanData'
        description: 粉丝数据
      introduction:
        description: 个人简介
        type: string
      nick_name:
        description: 昵称
        type: string
      room_sys_id:
        description: Room Id
        type: string
      sex:
        description: 性别 male:男;female:女; unknown:未知 保密
        type: string
      user_sys_id:
        description: uid 用户id
        type: string
    type: object
  user.GetVerifyCodeReq:
    properties:
      account:
        description: 登录账号
        type: string
      area_code:
        description: 区号,如果是手机号 传 区号，如果是邮箱 传 邮箱服务商 gmail、qq、outlook 等
        type: string
      identity_type:
        description: 登录类型，mobile_phone、email 目前只有 mobile_phone
        type: string
      scene:
        description: 场景 login 登录、reset_password 重置密码
        type: string
    required:
    - account
    - area_code
    - identity_type
    - scene
    type: object
  user.GetVerifyCodeResp:
    properties:
      is_new:
        description: |-
          验证码
          Code string `json:"code"`
          是否是新用户
        type: boolean
      ttl:
        description: 验证码有效时长
        type: integer
    type: object
  user.ResetPasswordReq:
    properties:
      identity_type:
        description: 登录类型，mobile_phone、email 目前只有 mobile_phone
        type: string
      new_password:
        description: 新密码 前端 必须进行 sha256 hash 后传过来 【小写】
        type: string
      verify_hash:
        description: 验证码 hash, 会在验证码验证没问题后返回，代表验证成功
        type: string
    required:
    - identity_type
    - new_password
    - verify_hash
    type: object
  user.ResetPasswordResp:
    type: object
  user.ThirdUserLoginReq:
    properties:
      firebase_token:
        description: firebase token
        type: string
      identity_type:
        description: '@Summary 第三方登录类型 apple、google'
        type: string
      third_token:
        description: 第三方登录 token
        type: string
    required:
    - identity_type
    - third_token
    type: object
  user.ThirdUserLoginResp:
    properties:
      is_new:
        description: 是否是新用户
        type: boolean
      token:
        description: 用户登录成功的 token
        type: string
    type: object
  user.UserFanData:
    properties:
      each_other_count:
        description: 相互关注数量
        type: integer
      fan_count:
        description: 粉丝数
        type: integer
      follow_count:
        description: 关注数
        type: integer
    type: object
  user.UserLoginReq:
    properties:
      account:
        description: 登录账号
        type: string
      area_code:
        description: 区号,如果是手机号 传 区号，如果是邮箱 传 邮箱服务商 gmail、qq、outlook 等
        type: string
      code:
        description: 验证码
        type: string
      identity_type:
        description: 登录类型，mobile_phone、email 目前只有 mobile_phone
        type: string
      login_type:
        description: 登录方式 password 密码登录、verify_code 验证码登录
        type: string
      password:
        description: |-
          登录密码，前端 必须进行 sha256 hash 后传过来 【小写】
          1. 如果账号存在的时候登录，密码 或者验证码必须有一个
          2. 如果获取 验证码登录的时候，获取验证码返回的是新用户，需要设置密码，也是使用该字段
        type: string
    required:
    - account
    - area_code
    - identity_type
    - login_type
    type: object
  user.UserLoginResp:
    properties:
      is_new:
        description: 是否是新用户
        type: boolean
      token:
        description: 用户登录成功的 token
        type: string
      user_sys_id:
        description: uid 用户id
        type: string
    type: object
info:
  contact: {}
paths:
  /app/sms_country_list:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 国家列表
          schema:
            $ref: '#/definitions/response.SmsCountryListResp'
      summary: 获取短信支持的国家 code 列表
      tags:
      - app
  /app/test:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: app test 接口
      tags:
      - app
  /room/create_room:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建房间
        in: body
        name: CreateRoomReq
        required: true
        schema:
          $ref: '#/definitions/room.CreateRoomReq'
      - description: 登录Token
        in: header
        name: X-Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/room.CreateRoomResp'
      summary: 创建房间
      tags:
      - room
  /room/get_room_base_info:
    post:
      consumes:
      - application/json
      parameters:
      - description: 房间基础信息
        in: body
        name: RoomBasenfoReq
        required: true
        schema:
          $ref: '#/definitions/room.RoomBasenfoReq'
      - description: 登录Token
        in: header
        name: X-Token
        required: true
        type: string
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/room.RoomBasenfoResp'
      summary: 获取房间基础信息
      tags:
      - room
  /room/room_list:
    post:
      consumes:
      - application/json
      parameters:
      - description: 房间列表
        in: body
        name: RoomListReq
        required: true
        schema:
          $ref: '#/definitions/room.RoomListReq'
      - description: 登录Token
        in: header
        name: X-Token
        required: true
        type: string
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/room.RoomListResp'
      summary: 房间列表
      tags:
      - room
  /sys/get_sys_config:
    post:
      consumes:
      - application/json
      parameters:
      - description: 获取系统配置
        in: body
        name: GetSysConfigReq
        required: true
        schema:
          $ref: '#/definitions/sys.GetSysConfigReq'
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      - description: 登录Token
        in: header
        name: X-Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/sys.GetSysConfigResp'
      summary: 返回前端使用的系统配置
      tags:
      - sys
  /user/account_verify_code:
    post:
      consumes:
      - application/json
      parameters:
      - description: 验证登录账号的验证码
        in: body
        name: ChangePassword
        required: true
        schema:
          $ref: '#/definitions/user.AccountVerifyCodeReq'
      - description: 登录Token
        in: header
        name: X-Token
        required: true
        type: string
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/user.AccountVerifyCodeResp'
      summary: 验证登录账号的验证码是否有效
      tags:
      - user
  /user/change_password:
    post:
      consumes:
      - application/json
      parameters:
      - description: 修改密码
        in: body
        name: ChangePassword
        required: true
        schema:
          $ref: '#/definitions/user.ChangePasswordReq'
      - description: 登录Token
        in: header
        name: X-Token
        required: true
        type: string
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/user.ChangePasswordResp'
      summary: 修改用户密码
      tags:
      - user
  /user/get_rc_user_token:
    post:
      consumes:
      - application/json
      parameters:
      - description: 获取user token
        in: body
        name: GetUserToken
        required: true
        schema:
          $ref: '#/definitions/rc.GetUserTokenReq'
      - description: 登录Token
        in: header
        name: X-Token
        required: true
        type: string
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            $ref: '#/definitions/rc.GetUserTokenResp'
      summary: 获取融云用户 token
      tags:
      - user
  /user/get_user_info:
    post:
      consumes:
      - application/json
      parameters:
      - description: 获取用户休息
        in: body
        name: ResetPassword
        required: true
        schema:
          $ref: '#/definitions/user.GetUserInfoReq'
      - description: 登录Token
        in: header
        name: X-Token
        required: true
        type: string
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/user.GetUserInfoResp'
      summary: 获取用户信息
      tags:
      - user
  /user/get_verify_code:
    post:
      consumes:
      - application/json
      parameters:
      - description: 获取验证码
        in: body
        name: GetVerifyCode
        required: true
        schema:
          $ref: '#/definitions/user.GetVerifyCodeReq'
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            $ref: '#/definitions/user.GetVerifyCodeResp'
      summary: 获取验证码
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户登录
        in: body
        name: LoginReq
        required: true
        schema:
          $ref: '#/definitions/user.UserLoginReq'
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/user.UserLoginResp'
      summary: 手机\邮箱验证码登录
      tags:
      - user
  /user/reset_password:
    post:
      consumes:
      - application/json
      parameters:
      - description: 重置密码
        in: body
        name: ResetPassword
        required: true
        schema:
          $ref: '#/definitions/user.ResetPasswordReq'
      - description: 登录Token
        in: header
        name: X-Token
        required: true
        type: string
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/user.ResetPasswordResp'
      summary: 重置用户密码
      tags:
      - user
  /user/third_login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 第三方用户登录
        in: body
        name: ThirdLoginReq
        required: true
        schema:
          $ref: '#/definitions/user.ThirdUserLoginReq'
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/user.ThirdUserLoginResp'
      summary: 第三方登录登录
      tags:
      - user
swagger: "2.0"
