definitions:
  user.GetUserInfoReq:
    type: object
  user.GetUserInfoResp:
    properties:
      avatar:
        description: 头像
        type: string
      birthday:
        description: 生日年-月-日
        type: string
      introduction:
        description: 个人简介
        type: string
      nick_name:
        description: 昵称
        type: string
      sex:
        description: 性别 male:男;female:女; unknown:未知 保密
        type: string
      user_sys_id:
        description: uid 用户id
        type: string
    type: object
  user.UserLoginReq:
    properties:
      account:
        description: 登录账号
        type: string
      area_code:
        description: 区号,如果是手机号 传 区号，如果是邮箱 传 邮箱服务商 gmail、qq、outlook 等
        type: string
      password:
        description: 登录密码，前端 必须进行 sha256 hash 后传过来 【小写】
        type: string
    required:
    - account
    - area_code
    type: object
  user.UserLoginResp:
    properties:
      is_new:
        description: 是否是新用户
        type: boolean
      token:
        description: 用户登录成功的 token
        type: string
      user_sys_id:
        description: uid 用户id
        type: string
    type: object
info:
  contact: {}
paths:
  /app/test:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: app test 接口
      tags:
      - app
  /user/info:
    post:
      consumes:
      - application/json
      parameters:
      - description: 获取登录用户
        in: body
        name: GetUserInfo
        required: true
        schema:
          $ref: '#/definitions/user.GetUserInfoReq'
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/user.GetUserInfoResp'
      summary: 获取登录用户
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户登录
        in: body
        name: LoginReq
        required: true
        schema:
          $ref: '#/definitions/user.UserLoginReq'
      - description: 请求ID
        in: header
        name: request_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/user.UserLoginResp'
      summary: 手机\邮箱验证码登录
      tags:
      - user
swagger: "2.0"
